import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import SideBar from "../components/dashboard/SideBar";
import AuthProviders from "../provider/AuthProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <AuthProviders>
          <div className="w-full p-10">
            <SideBar />
            {children}
          </div>
        </AuthProviders>
      </body>
    </html>
  );
}
