import { Inter } from "next/font/google";
import "./globals.css"
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AuthProviders from "../provider/AuthProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProviders session={session}>
          <div className="px-40 py-5">
            <Navbar />
            {children}
            <Footer />
          </div>
        </AuthProviders>
      </body>
    </html>
  );
}
